spring:
  datasource:
    url: jdbc:postgresql://localhost/estoque
    username: postgres
    password: aoc
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
